/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Jorge
 */
public class NivelPrincipiante extends javax.swing.JFrame {

    /**
     * Creates new form NivelPrincipiante
     */
    public NivelPrincipiante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtN1S1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtN2S2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNRS1 = new javax.swing.JTextField();
        txtN1S2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtN2S1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNRS2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtN1R1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtN2R1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNRR1 = new javax.swing.JTextField();
        txtN1R2 = new javax.swing.JTextField();
        txtNRR2 = new javax.swing.JTextField();
        txtN2R2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtN1M1 = new javax.swing.JTextField();
        txtNRM1 = new javax.swing.JTextField();
        txtN2M1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtN1D1 = new javax.swing.JTextField();
        btnVerificarSumas = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtN2D1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtNRD1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("NIVEL PRINCIPIANTE");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel2.setText("Nota: responde correctamente las operaciones que salen a continuacion");

        jLabel3.setText("SUMAS ");

        txtN1S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtN1S1ActionPerformed(evt);
            }
        });

        jLabel4.setText("+");

        txtN2S2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtN2S2ActionPerformed(evt);
            }
        });

        jLabel5.setText("=");

        txtNRS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNRS1ActionPerformed(evt);
            }
        });

        txtN1S2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtN1S2ActionPerformed(evt);
            }
        });

        jLabel6.setText("+");

        txtN2S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtN2S1ActionPerformed(evt);
            }
        });

        jLabel7.setText("=");

        txtNRS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNRS2ActionPerformed(evt);
            }
        });

        jLabel8.setText("RESTAS");

        txtN1R1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtN1R1ActionPerformed(evt);
            }
        });

        jLabel9.setText("-");

        txtN2R1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtN2R1ActionPerformed(evt);
            }
        });

        jLabel10.setText("=");

        txtNRR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNRR1ActionPerformed(evt);
            }
        });

        txtN1R2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtN1R2ActionPerformed(evt);
            }
        });

        txtNRR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNRR2ActionPerformed(evt);
            }
        });

        txtN2R2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtN2R2ActionPerformed(evt);
            }
        });

        jLabel11.setText("-");

        jLabel12.setText("=");

        jLabel13.setText("MULTIPLICACION");

        txtN1M1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtN1M1ActionPerformed(evt);
            }
        });

        txtNRM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNRM1ActionPerformed(evt);
            }
        });

        txtN2M1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtN2M1ActionPerformed(evt);
            }
        });

        jLabel14.setText("*");

        jLabel15.setText("=");

        jLabel16.setText("DIVISION");

        txtN1D1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtN1D1ActionPerformed(evt);
            }
        });

        btnVerificarSumas.setText("VERIFICAR");
        btnVerificarSumas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarSumasActionPerformed(evt);
            }
        });

        jLabel17.setText("/");

        txtN2D1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtN2D1ActionPerformed(evt);
            }
        });

        jLabel18.setText("=");

        txtNRD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNRD1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtN1M1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtN2M1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtN1S2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtN1S1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtN2S1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtNRS1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(157, 157, 157)
                                                .addComponent(txtN1R1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addGap(42, 42, 42)
                                                        .addComponent(jLabel15)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtNRM1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel6)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(txtN2S2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabel7)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(txtNRS2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtN1R2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtN1D1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel11)
                                                    .addComponent(jLabel9))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(txtN2R1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabel10))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(txtN2R2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel12))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel16)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(txtN2D1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabel18)))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNRR2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNRR1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNRD1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(343, 343, 343)))))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(79, 79, 79))
            .addGroup(layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(btnVerificarSumas)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtN1S1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(txtNRS1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtN2S1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtN1R1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtN2R1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtNRR1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtN1S2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtN2S2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtNRS2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtN1R2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtN2R2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNRR2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtN1M1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtN2M1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNRM1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(txtN1D1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtN2D1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txtNRD1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnVerificarSumas)
                .addGap(25, 25, 25))
        );

        setBounds(0, 0, 560, 412);
    }// </editor-fold>//GEN-END:initComponents

    private void txtN1S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtN1S1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtN1S1ActionPerformed

    private void txtN2S2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtN2S2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtN2S2ActionPerformed

    private void txtNRS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNRS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNRS1ActionPerformed

    private void txtN1S2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtN1S2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtN1S2ActionPerformed

    private void txtN2S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtN2S1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtN2S1ActionPerformed

    private void txtNRS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNRS2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNRS2ActionPerformed

    private void txtN1R1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtN1R1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtN1R1ActionPerformed

    private void txtN2R1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtN2R1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtN2R1ActionPerformed

    private void txtNRR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNRR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNRR1ActionPerformed

    private void txtN1R2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtN1R2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtN1R2ActionPerformed

    private void txtNRR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNRR2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNRR2ActionPerformed

    private void txtN2R2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtN2R2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtN2R2ActionPerformed

    private void txtN1M1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtN1M1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtN1M1ActionPerformed

    private void txtNRM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNRM1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNRM1ActionPerformed

    private void txtN2M1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtN2M1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtN2M1ActionPerformed

    private void txtN1D1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtN1D1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtN1D1ActionPerformed

    private void txtN2D1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtN2D1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtN2D1ActionPerformed

    private void txtNRD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNRD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNRD1ActionPerformed

    private void btnVerificarSumasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarSumasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerificarSumasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NivelPrincipiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NivelPrincipiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NivelPrincipiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NivelPrincipiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NivelPrincipiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnVerificarSumas;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JOptionPane jOptionPane1;
    public javax.swing.JTextField txtN1D1;
    public javax.swing.JTextField txtN1M1;
    public javax.swing.JTextField txtN1R1;
    public javax.swing.JTextField txtN1R2;
    public javax.swing.JTextField txtN1S1;
    public javax.swing.JTextField txtN1S2;
    public javax.swing.JTextField txtN2D1;
    public javax.swing.JTextField txtN2M1;
    public javax.swing.JTextField txtN2R1;
    public javax.swing.JTextField txtN2R2;
    public javax.swing.JTextField txtN2S1;
    public javax.swing.JTextField txtN2S2;
    public javax.swing.JTextField txtNRD1;
    public javax.swing.JTextField txtNRM1;
    public javax.swing.JTextField txtNRR1;
    public javax.swing.JTextField txtNRR2;
    public javax.swing.JTextField txtNRS1;
    public javax.swing.JTextField txtNRS2;
    // End of variables declaration//GEN-END:variables
}
